---
title: "Lab 00 - Hello IDS!"
author: "Benji"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Peter Rabbit", "Benji", "Cameron", "Gregor", "Jamie"),
  github_username = c("mcgregors-garden", "BenjiEdmondson", "Carthur7777", "gregor-mackay",
                      "jd43"), 
  colour = c("powderblue", "orange", "navyblue", 
             "steelblue4", "purple"),
  hobby = c("Hopping", "Orienteering", "Rugby", 
            "Hockey", "cycling"),
  favourite_number = c(2, 9, 5, 7, 3)
  )

team_data 
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


*Bar graph of everyones favorite number.*

### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "Name", 
          y = "Favorite Number",
          title = "Favorite number from 1-10")
```

*Adding graph axis.*

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

*List from most to least popular.*
